[workspace]
members = [
    "measure",

    "tcp",
    "tcp-tokio",
    "tcp-tokio-rustls",
    "tcp-tokio-native-tls",

    "http-warp-rustls",
]

[profile.release]
incremental = false
codegen-units = 1
lto = true
